#!/bin/csh
alias cohrs_run ~mjc/cohrs/cohrs_run
rm -f 20s.log
cohrs_run 20.0  >& 20s.log
cohrs_run 20.5 >>& 20s.log
cohrs_run 21.0 >>& 20s.log
cohrs_run 21.5 >>& 20s.log
cohrs_run 22.0 >>& 20s.log
cohrs_run 22.5 >>& 20s.log
cohrs_run 23.0 >>& 20s.log
cohrs_run 23.5 >>& 20s.log
cohrs_run 24.0 >>& 20s.log
cohrs_run 24.5 >>& 20s.log
cohrs_run 25.0 >>& 20s.log
cohrs_run 25.5 >>& 20s.log
cohrs_run 26.0 >>& 20s.log
cohrs_run 26.5 >>& 20s.log
cohrs_run 27.0 >>& 20s.log
cohrs_run 27.5 >>& 20s.log
cohrs_run 28.0 >>& 20s.log
cohrs_run 28.5 >>& 20s.log
cohrs_run 29.0 >>& 20s.log
cohrs_run 29.5 >>& 20s.log
