#!/bin/csh
alias cohrs_run ~mjc/cohrs/cohrs_run
rm -f 40s.log
cohrs_run 40.0 >& 40s.log
cohrs_run 40.5 >>& 40s.log
cohrs_run 41.0 >>& 40s.log
cohrs_run 41.5 >>& 40s.log
cohrs_run 42.0 >>& 40s.log
cohrs_run 42.5 >>& 40s.log
cohrs_run 43.0 >>& 40s.log
cohrs_run 43.15 >>& 40s.log
cohrs_run 43.5 >>& 40s.log
cohrs_run 44.13 >>& 40s.log
cohrs_run 44.88 >>& 40s.log
cohrs_run 45.5 >>& 40s.log
cohrs_run 45.85 >>& 40s.log
cohrs_run 46.5 >>& 40s.log
cohrs_run 47.5 >>& 40s.log
cohrs_run 48.5 >>& 40s.log
cohrs_run 49.5 >>& 40s.log
